[package]
name = "markdown-peek"
version = "0.1.3"
edition = "2024"
authors = ["tkcd <goriponikeike55@gmail.com>"]
repository = "https://github.com/takeshid/markdown-peek"
keywords = ["markdown", "cli"]
license-file = "LICENSE"
readme = "README.md"
description = "Markdown preview in browser and terminal"

[dependencies]
anyhow = "1.0.100"
axum = { version = "0.8.7", features = ["ws", "macros"] }
clap = { version = "4.5.53", features = ["derive"] }
futures = "0.3.31"
notify = "8.2.0"
notify-debouncer-mini = "0.7.0"
owo-colors = "4.2.3"
pulldown-cmark = { version = "0.13.0", features = ["serde"] }
pulldown-cmark-escape = "0.11.0"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
toml = "0.9.8"
tower-http = { version = "0.6.8", features = ["fs"] }
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
walkdir = "2.5.0"

[[bin]]
name = "mdpeek"
path = "src/main.rs"
